server.port= 8081

# App Properties
military.app.jwtSecret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
military.app.jwtExpirationMs= 86400000
#86400000

military.app.dynamodb.region=${DYNAMODB_REGION:${AWS_REGION:ap-southeast-1}}
military.app.dynamodb.endpoint=${DYNAMODB_ENDPOINT:}
military.app.dynamodb.tables.users=${DYNAMODB_USERS_TABLE:users}
military.app.dynamodb.tables.roles=${DYNAMODB_ROLES_TABLE:roles}
military.app.dynamodb.tables.personnel=${DYNAMODB_PERSONNEL_TABLE:military_personnel}

spring.messages.basename=messages
spring.messages.encoding=UTF-8
military.app.s3.bucket=${S3_BUCKET:}
military.app.s3.prefix=${S3_PREFIX:personnel}
military.app.s3.region=${S3_REGION:${AWS_REGION:ap-southeast-1}}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
