server.port= 8081

# App Properties
military.app.jwtSecret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
military.app.jwtExpirationMs= 86400000
#86400000

military.app.dynamodb.region=${DYNAMODB_REGION:${AWS_REGION:ap-southeast-1}}
military.app.dynamodb.endpoint=${DYNAMODB_ENDPOINT:}
military.app.dynamodb.tables.users=${DYNAMODB_USERS_TABLE:users}
military.app.dynamodb.tables.roles=${DYNAMODB_ROLES_TABLE:roles}
military.app.dynamodb.tables.personnel=${DYNAMODB_PERSONNEL_TABLE:military_personnel}
military.app.dynamodb.tables.regions=${DYNAMODB_REGIONS_TABLE:military_regions}
military.app.dynamodb.tables.units=${DYNAMODB_UNITS_TABLE:military_units}
military.app.dynamodb.tables.submission_groups=${DYNAMODB_SUBMISSION_GROUPS_TABLE:submission_groups}
military.app.dynamodb.tables.submission_flows=${DYNAMODB_SUBMISSION_FLOWS_TABLE:submission_flows}
military.app.dynamodb.tables.leave_approval_configs=${DYNAMODB_LEAVE_APPROVAL_CONFIGS_TABLE:leave_approval_configs}

spring.messages.basename=messages
spring.messages.encoding=UTF-8
military.app.s3.bucket=${S3_BUCKET:}
military.app.s3.prefix=${S3_PREFIX:personnel}
military.app.s3.region-prefix=${S3_REGION_PREFIX:military-regions}
military.app.s3.unit-prefix=${S3_UNIT_PREFIX:military-units}
military.app.s3.region=${S3_REGION:${AWS_REGION:ap-southeast-1}}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=../v3/api-docs
springdoc.swagger-ui.config-url=../v3/api-docs/swagger-config
